/*
 * RESTful Manager API
 * This page provides an **interactive** documentation for RESTful Manager API. In addition to the typical information provided for each operation (parameters, responses, etc.), you can experiment with it by setting parameters and clicking the `Try it out!` button. The operation will be invoked, and you'll see the response code and body, as well as the `curl` command and request URL which were used to invoke the command.  Furthermore, since this API was created using [Swagger](http://swagger.io), you can also download its [specification](xap-manager-api.yaml) and use Swagger's [Online Editor](http://editor.swagger.io) to generate a client in your favorite language. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DeploymentSLA
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-15T10:53:27.384Z")
public class DeploymentSLA {
  @SerializedName("requiresIsolation")
  private Boolean requiresIsolation = null;

  @SerializedName("zones")
  private List<String> zones = new ArrayList<String>();

  @SerializedName("maxInstancesPerVM")
  private Integer maxInstancesPerVM = null;

  @SerializedName("maxInstancesPerMachine")
  private Integer maxInstancesPerMachine = null;

  public DeploymentSLA requiresIsolation(Boolean requiresIsolation) {
    this.requiresIsolation = requiresIsolation;
    return this;
  }

   /**
   * Indicates instances of this deployment should be provisioned in an isolated container, i.e. without any other instances at the same container.
   * @return requiresIsolation
  **/
  @ApiModelProperty(required = true, value = "Indicates instances of this deployment should be provisioned in an isolated container, i.e. without any other instances at the same container.")
  public Boolean getRequiresIsolation() {
    return requiresIsolation;
  }

  public void setRequiresIsolation(Boolean requiresIsolation) {
    this.requiresIsolation = requiresIsolation;
  }

  public DeploymentSLA zones(List<String> zones) {
    this.zones = zones;
    return this;
  }

  public DeploymentSLA addZonesItem(String zonesItem) {
    this.zones.add(zonesItem);
    return this;
  }

   /**
   * List of zones this deployments can be provisioned within
   * @return zones
  **/
  @ApiModelProperty(required = true, value = "List of zones this deployments can be provisioned within")
  public List<String> getZones() {
    return zones;
  }

  public void setZones(List<String> zones) {
    this.zones = zones;
  }

  public DeploymentSLA maxInstancesPerVM(Integer maxInstancesPerVM) {
    this.maxInstancesPerVM = maxInstancesPerVM;
    return this;
  }

   /**
   * Maximum instances that can be deployed per VM
   * @return maxInstancesPerVM
  **/
  @ApiModelProperty(value = "Maximum instances that can be deployed per VM")
  public Integer getMaxInstancesPerVM() {
    return maxInstancesPerVM;
  }

  public void setMaxInstancesPerVM(Integer maxInstancesPerVM) {
    this.maxInstancesPerVM = maxInstancesPerVM;
  }

  public DeploymentSLA maxInstancesPerMachine(Integer maxInstancesPerMachine) {
    this.maxInstancesPerMachine = maxInstancesPerMachine;
    return this;
  }

   /**
   * Maximum instances that can be deployed per machine
   * @return maxInstancesPerMachine
  **/
  @ApiModelProperty(value = "Maximum instances that can be deployed per machine")
  public Integer getMaxInstancesPerMachine() {
    return maxInstancesPerMachine;
  }

  public void setMaxInstancesPerMachine(Integer maxInstancesPerMachine) {
    this.maxInstancesPerMachine = maxInstancesPerMachine;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentSLA deploymentSLA = (DeploymentSLA) o;
    return Objects.equals(this.requiresIsolation, deploymentSLA.requiresIsolation) &&
        Objects.equals(this.zones, deploymentSLA.zones) &&
        Objects.equals(this.maxInstancesPerVM, deploymentSLA.maxInstancesPerVM) &&
        Objects.equals(this.maxInstancesPerMachine, deploymentSLA.maxInstancesPerMachine);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requiresIsolation, zones, maxInstancesPerVM, maxInstancesPerMachine);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentSLA {\n");
    
    sb.append("    requiresIsolation: ").append(toIndentedString(requiresIsolation)).append("\n");
    sb.append("    zones: ").append(toIndentedString(zones)).append("\n");
    sb.append("    maxInstancesPerVM: ").append(toIndentedString(maxInstancesPerVM)).append("\n");
    sb.append("    maxInstancesPerMachine: ").append(toIndentedString(maxInstancesPerMachine)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

