/*
 * RESTful Manager API
 * This page provides an **interactive** documentation for RESTful Manager API. In addition to the typical information provided for each operation (parameters, responses, etc.), you can experiment with it by setting parameters and clicking the `Try it out!` button. The operation will be invoked, and you'll see the response code and body, as well as the `curl` command and request URL which were used to invoke the command.  Furthermore, since this API was created using [Swagger](http://swagger.io), you can also download its [specification](xap-manager-api.yaml) and use Swagger's [Online Editor](http://editor.swagger.io) to generate a client in your favorite language. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DeploymentInstanceContainer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-15T10:53:27.384Z")
public class DeploymentInstanceContainer {
  @SerializedName("id")
  private String id = null;

  @SerializedName("pid")
  private Integer pid = null;

  @SerializedName("zones")
  private List<String> zones = new ArrayList<String>();

  @SerializedName("deploymentInstances")
  private List<String> deploymentInstances = new ArrayList<String>();

  public DeploymentInstanceContainer id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Deployment instance container unique identifier
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Deployment instance container unique identifier")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DeploymentInstanceContainer pid(Integer pid) {
    this.pid = pid;
    return this;
  }

   /**
   * Deployment instance container Process id
   * @return pid
  **/
  @ApiModelProperty(required = true, value = "Deployment instance container Process id")
  public Integer getPid() {
    return pid;
  }

  public void setPid(Integer pid) {
    this.pid = pid;
  }

  public DeploymentInstanceContainer zones(List<String> zones) {
    this.zones = zones;
    return this;
  }

  public DeploymentInstanceContainer addZonesItem(String zonesItem) {
    this.zones.add(zonesItem);
    return this;
  }

   /**
   * Zones of the container
   * @return zones
  **/
  @ApiModelProperty(required = true, value = "Zones of the container")
  public List<String> getZones() {
    return zones;
  }

  public void setZones(List<String> zones) {
    this.zones = zones;
  }

  public DeploymentInstanceContainer deploymentInstances(List<String> deploymentInstances) {
    this.deploymentInstances = deploymentInstances;
    return this;
  }

  public DeploymentInstanceContainer addDeploymentInstancesItem(String deploymentInstancesItem) {
    this.deploymentInstances.add(deploymentInstancesItem);
    return this;
  }

   /**
   * List of deployment instances running within this container
   * @return deploymentInstances
  **/
  @ApiModelProperty(required = true, value = "List of deployment instances running within this container")
  public List<String> getDeploymentInstances() {
    return deploymentInstances;
  }

  public void setDeploymentInstances(List<String> deploymentInstances) {
    this.deploymentInstances = deploymentInstances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentInstanceContainer deploymentInstanceContainer = (DeploymentInstanceContainer) o;
    return Objects.equals(this.id, deploymentInstanceContainer.id) &&
        Objects.equals(this.pid, deploymentInstanceContainer.pid) &&
        Objects.equals(this.zones, deploymentInstanceContainer.zones) &&
        Objects.equals(this.deploymentInstances, deploymentInstanceContainer.deploymentInstances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, pid, zones, deploymentInstances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentInstanceContainer {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    zones: ").append(toIndentedString(zones)).append("\n");
    sb.append("    deploymentInstances: ").append(toIndentedString(deploymentInstances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

