/*
 * RESTful Manager API
 * This page provides an **interactive** documentation for RESTful Manager API. In addition to the typical information provided for each operation (parameters, responses, etc.), you can experiment with it by setting parameters and clicking the `Try it out!` button. The operation will be invoked, and you'll see the response code and body, as well as the `curl` command and request URL which were used to invoke the command.  Furthermore, since this API was created using [Swagger](http://swagger.io), you can also download its [specification](xap-manager-api.yaml) and use Swagger's [Online Editor](http://editor.swagger.io) to generate a client in your favorite language. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OperatingSystemStatistics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-15T10:53:27.384Z")
public class OperatingSystemStatistics {
  @SerializedName("timestamp")
  private Long timestamp = null;

  @SerializedName("adminTimestamp")
  private Long adminTimestamp = null;

  @SerializedName("freeSwapSpaceSizeInBytes")
  private Long freeSwapSpaceSizeInBytes = null;

  @SerializedName("freePhysicalMemorySizeInBytes")
  private Long freePhysicalMemorySizeInBytes = null;

  @SerializedName("actualFreePhysicalMemorySizeInBytes")
  private Long actualFreePhysicalMemorySizeInBytes = null;

  @SerializedName("physicalMemoryUsedPerc")
  private Double physicalMemoryUsedPerc = null;

  @SerializedName("cpuPerc")
  private Double cpuPerc = null;

  @SerializedName("cpuPercFormatted")
  private String cpuPercFormatted = null;

  @SerializedName("actualMemoryUsed")
  private Long actualMemoryUsed = null;

  public OperatingSystemStatistics timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp when the statistics were take
   * @return timestamp
  **/
  @ApiModelProperty(required = true, value = "The timestamp when the statistics were take")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public OperatingSystemStatistics adminTimestamp(Long adminTimestamp) {
    this.adminTimestamp = adminTimestamp;
    return this;
  }

   /**
   * The timestamp that is in sync with where the admin API is running. Can return -1 if the clocks have not sync yet
   * @return adminTimestamp
  **/
  @ApiModelProperty(required = true, value = "The timestamp that is in sync with where the admin API is running. Can return -1 if the clocks have not sync yet")
  public Long getAdminTimestamp() {
    return adminTimestamp;
  }

  public void setAdminTimestamp(Long adminTimestamp) {
    this.adminTimestamp = adminTimestamp;
  }

  public OperatingSystemStatistics freeSwapSpaceSizeInBytes(Long freeSwapSpaceSizeInBytes) {
    this.freeSwapSpaceSizeInBytes = freeSwapSpaceSizeInBytes;
    return this;
  }

   /**
   * Free swap space in bytes
   * @return freeSwapSpaceSizeInBytes
  **/
  @ApiModelProperty(required = true, value = "Free swap space in bytes")
  public Long getFreeSwapSpaceSizeInBytes() {
    return freeSwapSpaceSizeInBytes;
  }

  public void setFreeSwapSpaceSizeInBytes(Long freeSwapSpaceSizeInBytes) {
    this.freeSwapSpaceSizeInBytes = freeSwapSpaceSizeInBytes;
  }

  public OperatingSystemStatistics freePhysicalMemorySizeInBytes(Long freePhysicalMemorySizeInBytes) {
    this.freePhysicalMemorySizeInBytes = freePhysicalMemorySizeInBytes;
    return this;
  }

   /**
   * Free physical memory in bytes
   * @return freePhysicalMemorySizeInBytes
  **/
  @ApiModelProperty(required = true, value = "Free physical memory in bytes")
  public Long getFreePhysicalMemorySizeInBytes() {
    return freePhysicalMemorySizeInBytes;
  }

  public void setFreePhysicalMemorySizeInBytes(Long freePhysicalMemorySizeInBytes) {
    this.freePhysicalMemorySizeInBytes = freePhysicalMemorySizeInBytes;
  }

  public OperatingSystemStatistics actualFreePhysicalMemorySizeInBytes(Long actualFreePhysicalMemorySizeInBytes) {
    this.actualFreePhysicalMemorySizeInBytes = actualFreePhysicalMemorySizeInBytes;
    return this;
  }

   /**
   * Actual free physical memory in bytes
   * @return actualFreePhysicalMemorySizeInBytes
  **/
  @ApiModelProperty(required = true, value = "Actual free physical memory in bytes")
  public Long getActualFreePhysicalMemorySizeInBytes() {
    return actualFreePhysicalMemorySizeInBytes;
  }

  public void setActualFreePhysicalMemorySizeInBytes(Long actualFreePhysicalMemorySizeInBytes) {
    this.actualFreePhysicalMemorySizeInBytes = actualFreePhysicalMemorySizeInBytes;
  }

  public OperatingSystemStatistics physicalMemoryUsedPerc(Double physicalMemoryUsedPerc) {
    this.physicalMemoryUsedPerc = physicalMemoryUsedPerc;
    return this;
  }

   /**
   * The percentage used of physical memory out of the total physical memory space. Uses the total free memory e.g. e.g. Linux plus cached
   * @return physicalMemoryUsedPerc
  **/
  @ApiModelProperty(required = true, value = "The percentage used of physical memory out of the total physical memory space. Uses the total free memory e.g. e.g. Linux plus cached")
  public Double getPhysicalMemoryUsedPerc() {
    return physicalMemoryUsedPerc;
  }

  public void setPhysicalMemoryUsedPerc(Double physicalMemoryUsedPerc) {
    this.physicalMemoryUsedPerc = physicalMemoryUsedPerc;
  }

  public OperatingSystemStatistics cpuPerc(Double cpuPerc) {
    this.cpuPerc = cpuPerc;
    return this;
  }

   /**
   * The combined cpu perc (User + Sys + Nice + Wait)
   * @return cpuPerc
  **/
  @ApiModelProperty(required = true, value = "The combined cpu perc (User + Sys + Nice + Wait)")
  public Double getCpuPerc() {
    return cpuPerc;
  }

  public void setCpuPerc(Double cpuPerc) {
    this.cpuPerc = cpuPerc;
  }

  public OperatingSystemStatistics cpuPercFormatted(String cpuPercFormatted) {
    this.cpuPercFormatted = cpuPercFormatted;
    return this;
  }

   /**
   * The combined cpu formatted
   * @return cpuPercFormatted
  **/
  @ApiModelProperty(required = true, value = "The combined cpu formatted")
  public String getCpuPercFormatted() {
    return cpuPercFormatted;
  }

  public void setCpuPercFormatted(String cpuPercFormatted) {
    this.cpuPercFormatted = cpuPercFormatted;
  }

  public OperatingSystemStatistics actualMemoryUsed(Long actualMemoryUsed) {
    this.actualMemoryUsed = actualMemoryUsed;
    return this;
  }

   /**
   * Actual Memory Used, in bytes
   * @return actualMemoryUsed
  **/
  @ApiModelProperty(required = true, value = "Actual Memory Used, in bytes")
  public Long getActualMemoryUsed() {
    return actualMemoryUsed;
  }

  public void setActualMemoryUsed(Long actualMemoryUsed) {
    this.actualMemoryUsed = actualMemoryUsed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperatingSystemStatistics operatingSystemStatistics = (OperatingSystemStatistics) o;
    return Objects.equals(this.timestamp, operatingSystemStatistics.timestamp) &&
        Objects.equals(this.adminTimestamp, operatingSystemStatistics.adminTimestamp) &&
        Objects.equals(this.freeSwapSpaceSizeInBytes, operatingSystemStatistics.freeSwapSpaceSizeInBytes) &&
        Objects.equals(this.freePhysicalMemorySizeInBytes, operatingSystemStatistics.freePhysicalMemorySizeInBytes) &&
        Objects.equals(this.actualFreePhysicalMemorySizeInBytes, operatingSystemStatistics.actualFreePhysicalMemorySizeInBytes) &&
        Objects.equals(this.physicalMemoryUsedPerc, operatingSystemStatistics.physicalMemoryUsedPerc) &&
        Objects.equals(this.cpuPerc, operatingSystemStatistics.cpuPerc) &&
        Objects.equals(this.cpuPercFormatted, operatingSystemStatistics.cpuPercFormatted) &&
        Objects.equals(this.actualMemoryUsed, operatingSystemStatistics.actualMemoryUsed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, adminTimestamp, freeSwapSpaceSizeInBytes, freePhysicalMemorySizeInBytes, actualFreePhysicalMemorySizeInBytes, physicalMemoryUsedPerc, cpuPerc, cpuPercFormatted, actualMemoryUsed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperatingSystemStatistics {\n");
    
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    adminTimestamp: ").append(toIndentedString(adminTimestamp)).append("\n");
    sb.append("    freeSwapSpaceSizeInBytes: ").append(toIndentedString(freeSwapSpaceSizeInBytes)).append("\n");
    sb.append("    freePhysicalMemorySizeInBytes: ").append(toIndentedString(freePhysicalMemorySizeInBytes)).append("\n");
    sb.append("    actualFreePhysicalMemorySizeInBytes: ").append(toIndentedString(actualFreePhysicalMemorySizeInBytes)).append("\n");
    sb.append("    physicalMemoryUsedPerc: ").append(toIndentedString(physicalMemoryUsedPerc)).append("\n");
    sb.append("    cpuPerc: ").append(toIndentedString(cpuPerc)).append("\n");
    sb.append("    cpuPercFormatted: ").append(toIndentedString(cpuPercFormatted)).append("\n");
    sb.append("    actualMemoryUsed: ").append(toIndentedString(actualMemoryUsed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

