/*
 * RESTful Manager API
 * This page provides an **interactive** documentation for RESTful Manager API. In addition to the typical information provided for each operation (parameters, responses, etc.), you can experiment with it by setting parameters and clicking the `Try it out!` button. The operation will be invoked, and you'll see the response code and body, as well as the `curl` command and request URL which were used to invoke the command.  Furthermore, since this API was created using [Swagger](http://swagger.io), you can also download its [specification](xap-manager-api.yaml) and use Swagger's [Online Editor](http://editor.swagger.io) to generate a client in your favorite language. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OperatingSystemDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-15T10:53:27.384Z")
public class OperatingSystemDetails {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("timeDelta")
  private Long timeDelta = null;

  @SerializedName("currentTimeInMillis")
  private Long currentTimeInMillis = null;

  @SerializedName("arch")
  private String arch = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("availableProcessors")
  private Integer availableProcessors = null;

  @SerializedName("totalSwapSpaceSizeInBytes")
  private Long totalSwapSpaceSizeInBytes = null;

  @SerializedName("totalPhysicalMemorySizeInBytes")
  private Long totalPhysicalMemorySizeInBytes = null;

  @SerializedName("hostName")
  private String hostName = null;

  @SerializedName("hostAddress")
  private String hostAddress = null;

  @SerializedName("vendor")
  private String vendor = null;

  @SerializedName("vendorCodeName")
  private String vendorCodeName = null;

  @SerializedName("vendorName")
  private String vendorName = null;

  @SerializedName("vendorVersion")
  private String vendorVersion = null;

  public OperatingSystemDetails id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The uid of the operating system.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The uid of the operating system.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OperatingSystemDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the operating system.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of the operating system.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OperatingSystemDetails timeDelta(Long timeDelta) {
    this.timeDelta = timeDelta;
    return this;
  }

   /**
   * The delta between a current time taken on the admin API side, and the current time assumed by the remote machine
   * @return timeDelta
  **/
  @ApiModelProperty(required = true, value = "The delta between a current time taken on the admin API side, and the current time assumed by the remote machine")
  public Long getTimeDelta() {
    return timeDelta;
  }

  public void setTimeDelta(Long timeDelta) {
    this.timeDelta = timeDelta;
  }

  public OperatingSystemDetails currentTimeInMillis(Long currentTimeInMillis) {
    this.currentTimeInMillis = currentTimeInMillis;
    return this;
  }

   /**
   * Current time of the machine in millis
   * @return currentTimeInMillis
  **/
  @ApiModelProperty(required = true, value = "Current time of the machine in millis")
  public Long getCurrentTimeInMillis() {
    return currentTimeInMillis;
  }

  public void setCurrentTimeInMillis(Long currentTimeInMillis) {
    this.currentTimeInMillis = currentTimeInMillis;
  }

  public OperatingSystemDetails arch(String arch) {
    this.arch = arch;
    return this;
  }

   /**
   * The architecture of the operating system
   * @return arch
  **/
  @ApiModelProperty(required = true, value = "The architecture of the operating system")
  public String getArch() {
    return arch;
  }

  public void setArch(String arch) {
    this.arch = arch;
  }

  public OperatingSystemDetails version(String version) {
    this.version = version;
    return this;
  }

   /**
   * The version of the operating system
   * @return version
  **/
  @ApiModelProperty(required = true, value = "The version of the operating system")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public OperatingSystemDetails availableProcessors(Integer availableProcessors) {
    this.availableProcessors = availableProcessors;
    return this;
  }

   /**
   * The number of available processors
   * @return availableProcessors
  **/
  @ApiModelProperty(required = true, value = "The number of available processors")
  public Integer getAvailableProcessors() {
    return availableProcessors;
  }

  public void setAvailableProcessors(Integer availableProcessors) {
    this.availableProcessors = availableProcessors;
  }

  public OperatingSystemDetails totalSwapSpaceSizeInBytes(Long totalSwapSpaceSizeInBytes) {
    this.totalSwapSpaceSizeInBytes = totalSwapSpaceSizeInBytes;
    return this;
  }

   /**
   * The total swap space size (in Bytes)
   * @return totalSwapSpaceSizeInBytes
  **/
  @ApiModelProperty(required = true, value = "The total swap space size (in Bytes)")
  public Long getTotalSwapSpaceSizeInBytes() {
    return totalSwapSpaceSizeInBytes;
  }

  public void setTotalSwapSpaceSizeInBytes(Long totalSwapSpaceSizeInBytes) {
    this.totalSwapSpaceSizeInBytes = totalSwapSpaceSizeInBytes;
  }

  public OperatingSystemDetails totalPhysicalMemorySizeInBytes(Long totalPhysicalMemorySizeInBytes) {
    this.totalPhysicalMemorySizeInBytes = totalPhysicalMemorySizeInBytes;
    return this;
  }

   /**
   * The total physical memory size (in Bytes)
   * @return totalPhysicalMemorySizeInBytes
  **/
  @ApiModelProperty(required = true, value = "The total physical memory size (in Bytes)")
  public Long getTotalPhysicalMemorySizeInBytes() {
    return totalPhysicalMemorySizeInBytes;
  }

  public void setTotalPhysicalMemorySizeInBytes(Long totalPhysicalMemorySizeInBytes) {
    this.totalPhysicalMemorySizeInBytes = totalPhysicalMemorySizeInBytes;
  }

  public OperatingSystemDetails hostName(String hostName) {
    this.hostName = hostName;
    return this;
  }

   /**
   * The (local) host name of the OS
   * @return hostName
  **/
  @ApiModelProperty(required = true, value = "The (local) host name of the OS")
  public String getHostName() {
    return hostName;
  }

  public void setHostName(String hostName) {
    this.hostName = hostName;
  }

  public OperatingSystemDetails hostAddress(String hostAddress) {
    this.hostAddress = hostAddress;
    return this;
  }

   /**
   * The (local) host address of the OS
   * @return hostAddress
  **/
  @ApiModelProperty(required = true, value = "The (local) host address of the OS")
  public String getHostAddress() {
    return hostAddress;
  }

  public void setHostAddress(String hostAddress) {
    this.hostAddress = hostAddress;
  }

  public OperatingSystemDetails vendor(String vendor) {
    this.vendor = vendor;
    return this;
  }

   /**
   * The vendor (e.g. Microsoft)
   * @return vendor
  **/
  @ApiModelProperty(required = true, value = "The vendor (e.g. Microsoft)")
  public String getVendor() {
    return vendor;
  }

  public void setVendor(String vendor) {
    this.vendor = vendor;
  }

  public OperatingSystemDetails vendorCodeName(String vendorCodeName) {
    this.vendorCodeName = vendorCodeName;
    return this;
  }

   /**
   * The vendor code-name (e.g. Whistler)
   * @return vendorCodeName
  **/
  @ApiModelProperty(required = true, value = "The vendor code-name (e.g. Whistler)")
  public String getVendorCodeName() {
    return vendorCodeName;
  }

  public void setVendorCodeName(String vendorCodeName) {
    this.vendorCodeName = vendorCodeName;
  }

  public OperatingSystemDetails vendorName(String vendorName) {
    this.vendorName = vendorName;
    return this;
  }

   /**
   * The vendor name (e.g. Microsoft XP)
   * @return vendorName
  **/
  @ApiModelProperty(required = true, value = "The vendor name (e.g. Microsoft XP)")
  public String getVendorName() {
    return vendorName;
  }

  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }

  public OperatingSystemDetails vendorVersion(String vendorVersion) {
    this.vendorVersion = vendorVersion;
    return this;
  }

   /**
   * vendor version (e.g. XP)
   * @return vendorVersion
  **/
  @ApiModelProperty(required = true, value = "vendor version (e.g. XP)")
  public String getVendorVersion() {
    return vendorVersion;
  }

  public void setVendorVersion(String vendorVersion) {
    this.vendorVersion = vendorVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperatingSystemDetails operatingSystemDetails = (OperatingSystemDetails) o;
    return Objects.equals(this.id, operatingSystemDetails.id) &&
        Objects.equals(this.name, operatingSystemDetails.name) &&
        Objects.equals(this.timeDelta, operatingSystemDetails.timeDelta) &&
        Objects.equals(this.currentTimeInMillis, operatingSystemDetails.currentTimeInMillis) &&
        Objects.equals(this.arch, operatingSystemDetails.arch) &&
        Objects.equals(this.version, operatingSystemDetails.version) &&
        Objects.equals(this.availableProcessors, operatingSystemDetails.availableProcessors) &&
        Objects.equals(this.totalSwapSpaceSizeInBytes, operatingSystemDetails.totalSwapSpaceSizeInBytes) &&
        Objects.equals(this.totalPhysicalMemorySizeInBytes, operatingSystemDetails.totalPhysicalMemorySizeInBytes) &&
        Objects.equals(this.hostName, operatingSystemDetails.hostName) &&
        Objects.equals(this.hostAddress, operatingSystemDetails.hostAddress) &&
        Objects.equals(this.vendor, operatingSystemDetails.vendor) &&
        Objects.equals(this.vendorCodeName, operatingSystemDetails.vendorCodeName) &&
        Objects.equals(this.vendorName, operatingSystemDetails.vendorName) &&
        Objects.equals(this.vendorVersion, operatingSystemDetails.vendorVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, timeDelta, currentTimeInMillis, arch, version, availableProcessors, totalSwapSpaceSizeInBytes, totalPhysicalMemorySizeInBytes, hostName, hostAddress, vendor, vendorCodeName, vendorName, vendorVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperatingSystemDetails {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    timeDelta: ").append(toIndentedString(timeDelta)).append("\n");
    sb.append("    currentTimeInMillis: ").append(toIndentedString(currentTimeInMillis)).append("\n");
    sb.append("    arch: ").append(toIndentedString(arch)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    availableProcessors: ").append(toIndentedString(availableProcessors)).append("\n");
    sb.append("    totalSwapSpaceSizeInBytes: ").append(toIndentedString(totalSwapSpaceSizeInBytes)).append("\n");
    sb.append("    totalPhysicalMemorySizeInBytes: ").append(toIndentedString(totalPhysicalMemorySizeInBytes)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    hostAddress: ").append(toIndentedString(hostAddress)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    vendorCodeName: ").append(toIndentedString(vendorCodeName)).append("\n");
    sb.append("    vendorName: ").append(toIndentedString(vendorName)).append("\n");
    sb.append("    vendorVersion: ").append(toIndentedString(vendorVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

