/*
 * RESTful Manager API
 * This page provides an **interactive** documentation for RESTful Manager API. In addition to the typical information provided for each operation (parameters, responses, etc.), you can experiment with it by setting parameters and clicking the `Try it out!` button. The operation will be invoked, and you'll see the response code and body, as well as the `curl` command and request URL which were used to invoke the command.  Furthermore, since this API was created using [Swagger](http://swagger.io), you can also download its [specification](xap-manager-api.yaml) and use Swagger's [Online Editor](http://editor.swagger.io) to generate a client in your favorite language. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SpaceTypeStatistics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-15T10:53:27.384Z")
public class SpaceTypeStatistics {
  @SerializedName("entries")
  private Integer entries = null;

  @SerializedName("notifyTemplates")
  private Integer notifyTemplates = null;

  public SpaceTypeStatistics entries(Integer entries) {
    this.entries = entries;
    return this;
  }

   /**
   * Total number of entries of this type in space
   * @return entries
  **/
  @ApiModelProperty(required = true, value = "Total number of entries of this type in space")
  public Integer getEntries() {
    return entries;
  }

  public void setEntries(Integer entries) {
    this.entries = entries;
  }

  public SpaceTypeStatistics notifyTemplates(Integer notifyTemplates) {
    this.notifyTemplates = notifyTemplates;
    return this;
  }

   /**
   * Total number of notify templates of this type in space
   * @return notifyTemplates
  **/
  @ApiModelProperty(required = true, value = "Total number of notify templates of this type in space")
  public Integer getNotifyTemplates() {
    return notifyTemplates;
  }

  public void setNotifyTemplates(Integer notifyTemplates) {
    this.notifyTemplates = notifyTemplates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpaceTypeStatistics spaceTypeStatistics = (SpaceTypeStatistics) o;
    return Objects.equals(this.entries, spaceTypeStatistics.entries) &&
        Objects.equals(this.notifyTemplates, spaceTypeStatistics.notifyTemplates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries, notifyTemplates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpaceTypeStatistics {\n");
    
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    notifyTemplates: ").append(toIndentedString(notifyTemplates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

