/*
 * RESTful Manager API
 * This page provides an **interactive** documentation for RESTful Manager API. In addition to the typical information provided for each operation (parameters, responses, etc.), you can experiment with it by setting parameters and clicking the `Try it out!` button. The operation will be invoked, and you'll see the response code and body, as well as the `curl` command and request URL which were used to invoke the command.  Furthermore, since this API was created using [Swagger](http://swagger.io), you can also download its [specification](xap-manager-api.yaml) and use Swagger's [Online Editor](http://editor.swagger.io) to generate a client in your favorite language. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SpaceInstance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-15T10:53:27.384Z")
public class SpaceInstance {
  @SerializedName("id")
  private String id = null;

  @SerializedName("mode")
  private String mode = null;

  @SerializedName("partitionId")
  private Integer partitionId = null;

  @SerializedName("backupId")
  private Integer backupId = null;

  @SerializedName("hostId")
  private String hostId = null;

  @SerializedName("containerId")
  private String containerId = null;

  public SpaceInstance id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Space Instance unique identifier
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Space Instance unique identifier")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SpaceInstance mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * space mode (primary, backup, none)
   * @return mode
  **/
  @ApiModelProperty(required = true, value = "space mode (primary, backup, none)")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public SpaceInstance partitionId(Integer partitionId) {
    this.partitionId = partitionId;
    return this;
  }

   /**
   * Partition Id
   * @return partitionId
  **/
  @ApiModelProperty(required = true, value = "Partition Id")
  public Integer getPartitionId() {
    return partitionId;
  }

  public void setPartitionId(Integer partitionId) {
    this.partitionId = partitionId;
  }

  public SpaceInstance backupId(Integer backupId) {
    this.backupId = backupId;
    return this;
  }

   /**
   * Backup id of instance within its partition
   * @return backupId
  **/
  @ApiModelProperty(required = true, value = "Backup id of instance within its partition")
  public Integer getBackupId() {
    return backupId;
  }

  public void setBackupId(Integer backupId) {
    this.backupId = backupId;
  }

  public SpaceInstance hostId(String hostId) {
    this.hostId = hostId;
    return this;
  }

   /**
   * The host id which the space deployed in
   * @return hostId
  **/
  @ApiModelProperty(required = true, value = "The host id which the space deployed in")
  public String getHostId() {
    return hostId;
  }

  public void setHostId(String hostId) {
    this.hostId = hostId;
  }

  public SpaceInstance containerId(String containerId) {
    this.containerId = containerId;
    return this;
  }

   /**
   * The container(gsc) id which the space deployed in
   * @return containerId
  **/
  @ApiModelProperty(required = true, value = "The container(gsc) id which the space deployed in")
  public String getContainerId() {
    return containerId;
  }

  public void setContainerId(String containerId) {
    this.containerId = containerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpaceInstance spaceInstance = (SpaceInstance) o;
    return Objects.equals(this.id, spaceInstance.id) &&
        Objects.equals(this.mode, spaceInstance.mode) &&
        Objects.equals(this.partitionId, spaceInstance.partitionId) &&
        Objects.equals(this.backupId, spaceInstance.backupId) &&
        Objects.equals(this.hostId, spaceInstance.hostId) &&
        Objects.equals(this.containerId, spaceInstance.containerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, mode, partitionId, backupId, hostId, containerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpaceInstance {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    partitionId: ").append(toIndentedString(partitionId)).append("\n");
    sb.append("    backupId: ").append(toIndentedString(backupId)).append("\n");
    sb.append("    hostId: ").append(toIndentedString(hostId)).append("\n");
    sb.append("    containerId: ").append(toIndentedString(containerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

